/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dsw5t_javarmi;

import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius
 */
public class TelaClient extends javax.swing.JFrame {

    /**
     * Creates new form TelaClient
     */
    HelloClient client;
    
    public TelaClient() {
        initComponents();
        client = new HelloClient();
        client.start(JOptionPane.showInputDialog("Server"), JOptionPane.showInputDialog("Porta"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfValor1 = new javax.swing.JTextField();
        jbDivide = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaLog = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jtfValor2 = new javax.swing.JTextField();
        jbSoma1 = new javax.swing.JButton();
        jbSubtrai1 = new javax.swing.JButton();
        jbMultiplica1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Valor 1");

        jtfValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValor1ActionPerformed(evt);
            }
        });

        jbDivide.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbDivide.setText("/");
        jbDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivideActionPerformed(evt);
            }
        });

        jtaLog.setColumns(20);
        jtaLog.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jtaLog.setRows(5);
        jScrollPane1.setViewportView(jtaLog);

        jLabel2.setText("Valor 2");

        jtfValor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValor2ActionPerformed(evt);
            }
        });

        jbSoma1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbSoma1.setText("+");
        jbSoma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSoma1ActionPerformed(evt);
            }
        });

        jbSubtrai1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbSubtrai1.setText("-");
        jbSubtrai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubtrai1ActionPerformed(evt);
            }
        });

        jbMultiplica1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbMultiplica1.setText("X");
        jbMultiplica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultiplica1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbSoma1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSubtrai1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbMultiplica1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jbDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfValor2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jtfValor1))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSoma1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSubtrai1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMultiplica1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfValor1ActionPerformed

    private void jtfValor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfValor2ActionPerformed

    private void jbDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivideActionPerformed
        // TODO add your handling code here:
        jtaLog.setText("");
        jtaLog.setText("Resultado: " + client.divide(
                            Integer.parseInt(jtfValor1.getText()), 
                            Integer.parseInt(jtfValor2.getText()))
                       );
    }//GEN-LAST:event_jbDivideActionPerformed

    private void jbSoma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSoma1ActionPerformed
        // TODO add your handling code here:
        jtaLog.setText("");
        jtaLog.setText("Resultado: " + client.soma(
                            Integer.parseInt(jtfValor1.getText()), 
                            Integer.parseInt(jtfValor2.getText()))
                       );
    }//GEN-LAST:event_jbSoma1ActionPerformed

    private void jbSubtrai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubtrai1ActionPerformed
        // TODO add your handling code here:
        jtaLog.setText("");
        jtaLog.setText("Resultado: " + client.subtrai(
                            Integer.parseInt(jtfValor1.getText()), 
                            Integer.parseInt(jtfValor2.getText()))
                       );
    }//GEN-LAST:event_jbSubtrai1ActionPerformed

    private void jbMultiplica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplica1ActionPerformed
        // TODO add your handling code here:
        jtaLog.setText("");
        jtaLog.setText("Resultado: " + client.multiplica(
                            Integer.parseInt(jtfValor1.getText()), 
                            Integer.parseInt(jtfValor2.getText()))
                       );
    }//GEN-LAST:event_jbMultiplica1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            //for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            //    if ("Nimbus".equals(info.getName())) {
            //        javax.swing.UIManager.setLookAndFeel(info.getClassName());
            //        break;
            //}
            //}
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDivide;
    private javax.swing.JButton jbMultiplica1;
    private javax.swing.JButton jbSoma1;
    private javax.swing.JButton jbSubtrai1;
    private javax.swing.JTextArea jtaLog;
    private javax.swing.JTextField jtfValor1;
    private javax.swing.JTextField jtfValor2;
    // End of variables declaration//GEN-END:variables
}
